[package]
name = "rbabel"
version = "0.1.0"
authors = ["ltj"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
predicates = "1.0.7"
